### ISSUE TITLE
Headers won't fit in PCB

### ISSUE THREAD

**Issue by elibdev** [caru/Stenoboard#1]
I'm currently assembling my Stenoboard v1.1, and I can't quite fit the square header pins into the holes they're supposed to fit in. With some pretty intense shoving, I managed to get a smaller one in, but just barely (pictured below). I'm afraid to just apply more force in case it breaks. Is there something I'm doing wrong?

![fullsizerender](https://cloud.githubusercontent.com/assets/4471727/7969541/88242d58-0a05-11e5-9d9f-a9513a2f198b.jpg)

Thanks!

**Comment by caru** [comment]
Answered privately, I changed the components and now they fit.

**Comment by elibdev** [comment]
Thanks Emanuelle!
